### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Viot-HUST** [xmed-lab/DIF-Net#1]
Hi, thank you for your nice work! Could you provide part of the dataset to facilitate testing?

**Comment by hyaihjq** [comment]
@lyqun Dataset can be share?

**Comment by lyqun** [comment]
Hi, we currently have no plans to make the data public since there are restrictions on the use of the data due to agreements with funding agencies. The preprocessing scripts are provided in ./data/knee_cbct/ and you can also run experiments on public CT datasets.

**Comment by qiaodongxing** [comment]
Hello, thank you for your beautiful work. When I used the public data set NSCLC to test the effect, I processed the data according to the steps you used to process the data and trained with the default parameters, but the contrast of the reconstructed image from the training result was very poor, which was far from the effect in the paper. Could you tell me where my problem was? When I used the public data set NSCLC to test the effect, the data was processed according to the steps you used to process the data and the default parameters were trained, but the contrast of the reconstructed image was poor, and it was far from the effect in the paper. Could you tell me where my problem was

**Comment by qiaodongxing** [comment]
Hello, thank you for your beautiful work. When I used the public data set NSCLC to test the effect, I processed the data according to the steps you used to process the data and trained with the default parameters, but the contrast of the reconstructed image from the training result was very poor, which was far from the effect in the paper. Could you tell me where my problem was?

**Comment by lyqun** [comment]
Thanks for your comments.

It seems that the method does not perform well on chest data. For your reference, we have conducted experiments on LUNA16, and PSNR/SSIM is 26.67/86.09 with 10 projection views.

**Comment by yuanpengpeng** [comment]
> Hello, thank you for your beautiful work. When I used the public data set NSCLC to test the effect, I processed the data according to the steps you used to process the data and trained with the default parameters, but the contrast of the reconstructed image from the training result was very poor, which was far from the effect in the paper. Could you tell me where my problem was?
##################
May I ask if you have encountered this error during your reasoning?

Namespace(name='dif-net', epoch=400, dst_list='knee_cbct', split='test', combine='mlp', num_views=3, view_offset=0, out_res=256, eval_npoint=100000, visualize=False)
mixed_dataset: ['knee_cbct']
输出dst_name: knee_cbct
CBCT_dataset, name: knee_cbct, split: test, len: 1.
load ckpt from /mnt/d/谷歌下载/DIF-Net-main/DIF-Net-main/scripts/logs/dif-net/ep_400.pth
DIF_Net, mid_ch: 128, combine: mlp
Traceback (most recent call last):
  File "/mnt/d/谷歌下载/DIF-Net-main/DIF-Net-main/code/evaluate.py", line 110, in <module>
    model.load_state_dict(ckpt)
  File "/home/yuanpeng/conda/envs/python310Tigre/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DIF_Net:
        size mismatch for view_mixer.layer.0.weight: copying a param with shape torch.Size([5, 10, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
        size mismatch for view_mixer.layer.0.bias: copying a param with shape torch.Size([5]) from checkpoint, the shape in current model is torch.Size([1]).
        size mismatch for view_mixer.layer.2.weight: copying a param with shape torch.Size([1, 5, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 1, 1, 1]).

**Comment by lyqun** [comment]
Did you modify some parameters (e.g., channels, number of layers) of the model? This error means that the parameters of some layers are not matched with the loaded checkpoint.

**Comment by yuanpengpeng** [comment]
No, I set it up exactly as in your paper. I re-tested it later. The training and testing are all the same checkpoint. However, with 24g of video memory, 10 views still cannot be accommodated, and only 4 views can be accommodated at most. In the case of 256*256*256 size




袁鹏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xmed-lab/DIF-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月15日(星期一) 中午1:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xmed-lab/DIF-Net] Dataset (Issue #1)





 
Did you modify some parameters (e.g., channels, number of layers) of the model? This error means that the parameters of some layers are not matched with the loaded checkpoint.
